fn expand(galaxy: &mut Vec<Vec<char>>) {
    
}

fn main() {
    let contents = std::fs::read_to_string("test1.txt").expect("Could not read file!");
    let mut contents: Vec<Vec<char>> = contents.lines().map(|x| x.chars().collect()).collect();
    
    for row in contents.iter() {
        println!("{:?}", row);
    }
    
    let compare = "....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......".lines().map(|x| x.chars().collect()).collect();
    
}
